CREATE TABLE IF NOT EXISTS `form_giexam` (
    /* both extended and encounter forms need a last modified date */
    date datetime default NULL comment 'last modified date',
    /* these fields are common to all encounter forms. */
    id bigint(20) NOT NULL auto_increment,
    pid bigint(20) NOT NULL default 0,
    user varchar(255) default NULL,
    groupname varchar(255) default NULL,
    authorized tinyint(4) default NULL,
    activity tinyint(4) default NULL,
    abd_upper varchar(255),
    abd_shape varchar(255),
    abd_flanks varchar(255),
    abd_umbi varchar(255),
    abd_scar varchar(255),
    abd_vein varchar(255),
    abd_movm varchar(255),
    abd_puls varchar(255),
    abd_peris varchar(255),
    abd_lump varchar(255),
    abd_parotid varchar(255),
    abd_spider varchar(255),
    abd_hernia varchar(255),
    abd_hair varchar(255),
    abd_genetalia varchar(255),
    abd_temp varchar(255),
    abd_tender varchar(255),
    abd_vflow varchar(255),
    abd_feel varchar(255),
    abd_loclump varchar(255),
    abd_girth varchar(255),
    abd_oedema varchar(255),
    abd_fthrill varchar(255),
    abd_liver TEXT,
    abd_gb TEXT,
    abd_spleen TEXT,
    abd_kidney TEXT,
    abd_nodes varchar(255),
    abd_tone varchar(255),
    abd_sdull varchar(255),
    abd_traube varchar(255),
    abd_psound varchar(255),
    abd_splash varchar(255),
    abd_bruit varchar(255),
    abd_spbruit varchar(255),
    abd_cbruit varchar(255),
    abd_auper varchar(255),
    abd_vnhum varchar(255),
    abd_epigast varchar(255),
    PRIMARY KEY (id)
) TYPE=InnoDB;
INSERT IGNORE INTO list_options SET list_id='lists',
    option_id='present_absent',
    title='Present Absent';
INSERT IGNORE INTO list_options SET list_id='present_absent',
    option_id='1',
    title='Present',
    seq='1';
INSERT IGNORE INTO list_options SET list_id='present_absent',
    option_id='2',
    title='Absent',
    seq='2';
INSERT IGNORE INTO list_options SET list_id='lists',
    option_id='flank_cond',
    title='Flank Condition';
INSERT IGNORE INTO list_options SET list_id='flank_cond',
    option_id='1',
    title='Full',
    seq='1';
INSERT IGNORE INTO list_options SET list_id='flank_cond',
    option_id='2',
    title='Not Full',
    seq='2';

